<CalibracaoPage>:
    name: "calibracaopage"
    
    BoxLayout:
        orientation: 'vertical'
        spacing: 0

        canvas.before:
            Color:
                rgba: 0.95, 0.96, 0.96, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # -------------------------------------------------------------
        # 1. CABEÇALHO SUPERIOR 
        # -------------------------------------------------------------
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.12
            padding: [15, 10, 15, 10]
            spacing: 12

            canvas.before:
                Color:
                    rgba: 0.38, 0.55, 0.28, 1 
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: 'vertical'
                alignment: 'center'

                Label:
                    text: "Sistema de Análise de Frutos"
                    font_size: '18sp'
                    bold: True
                    halign: 'center'
                    valign: 'bottom'
                    text_size: self.size
                    color: 1, 1, 1, 1

                Label:
                    text: "FIM"
                    font_size: '12sp'
                    halign: 'center'
                    valign: 'top'
                    text_size: self.size
                    color: 0.9, 0.95, 0.9, 1


        BoxLayout:
            orientation: "vertical"
            padding: dp(30)
            spacing: dp(15)
            size_hint_y: 0.79 
            
            Widget:
                size_hint_y: 0.1
                
            Label:
                text: "Calibração"
                font_size: '22sp'
                bold: True
                color: 0, 0, 0, 1
                size_hint_y: None
                height: dp(40)
                
            Label:
                text: "Digite o diâmetro (em mm) do objeto de\nreferência que você utilizará nas fotos:"
                halign: "center"
                color: 0.2, 0.2, 0.2, 1
                size_hint_y: None
                height: dp(50)
                
            TextInput:
                id: input_or
                hint_text: "Ex: 27.0"
                input_type: "number"
                multiline: False
                font_size: '20sp'
                halign: 'center'
                size_hint_y: None
                height: dp(45)
                size_hint_x: 0.5
                pos_hint: {'center_x': 0.5}
                
            Widget:
                size_hint_y: 0.1
                
            Button:
                text: "Salvar"
                size_hint: None, None
                size: dp(150), dp(45)
                pos_hint: {'center_x': 0.5}
                background_normal: ''
                background_color: 0.18, 0.49, 0.19, 1
                bold: True
                on_release: root.salvar_calibracao(input_or.text)
                
            Widget:
                size_hint_y: 0.4


        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.09
            padding: 20

            canvas.before:
                Color:
                    rgba: 0.38, 0.55, 0.28, 1 
                Rectangle:
                    pos: self.pos
                    size: self.size


            Button:
                background_normal: ''
                background_color: 0, 0, 0, 0
                on_release: app.mudar_tela("downloadpage")

                BoxLayout:
                    orientation: 'vertical'
                    pos: self.parent.pos
                    size: self.parent.size
                    padding: 5

                    Image:
                        source: 'imagens/baixar.png'
                        size_hint_y: 0.4
                        allow_stretch: True
                        keep_ratio: True


            Button:
                background_normal: ''
                background_color: 0, 0, 0, 0
                on_release: app.mudar_tela("homepage")

                BoxLayout:
                    orientation: 'vertical'
                    pos: self.parent.pos
                    size: self.parent.size
                    padding: 5

                    Image:
                        source: 'imagens/botao_inicio.png'
                        size_hint_y: 0.4
                        allow_stretch: True
                        keep_ratio: True


            Button:
                background_normal: ''
                background_color: 0, 0, 0, 0
                on_release: app.mudar_tela("instrucoespage")

                BoxLayout:
                    orientation: 'vertical'
                    pos: self.parent.pos
                    size: self.parent.size
                    padding: 5

                    Image:
                        source: 'imagens/livro.png'
                        size_hint_y: 0.4
                        allow_stretch: True
                        keep_ratio: True
